name: cuDF wheels

on:
  push:
    branches:
      - 'pull-request/[0-9]+'

jobs:
  cudf:
    uses: rapidsai/shared-action-workflows/.github/workflows/pr-wheels.yml@feat/wheel-ci-actions
    with:
      package-name: cudf
      package-dir: python/cudf
      cibw-before-all: "dnf install -y openssl-devel rapidjson-devel libzstd-devel lz4-devel lz4-libs protobuf-devel && tar -xf /opt/_internal/static-libs-for-embedding-only.tar.xz -C /opt/_internal"
      cibw-before-build: "pip install rmm-cuda11 --index-url https://pypi.k8s.rapids.ai/simple && pip install pyarrow==8.0.0 && export PYARROW_PYPI_DIR=$(python3 -c 'import pyarrow, os; print(os.path.dirname(pyarrow.__file__))')"
      skbuild-configure-options: "-DOPENSSL_SSL_LIBRARY=/usr/lib64/libssl.so -DOPENSSL_CRYPTO_LIBRARY=/usr/lib64/libcrypto.so -DArrow_DIR=\"${PYARROW_PYPI_DIR}\""
      manylinux-platform: manylinux_2_17
      cpu-smoketest-command: "python3 -c 'import cudf; print(cudf)'"
      gpu-smoketest-command: ""
    secrets: inherit
